### ISSUE TITLE
No longer functional Craft from Storage Mod

### ISSUE THREAD

**Issue by veronica-red** [devopsdinosaur/sunhaven-mods#2]
With the new update, this seems to be not working anymore. Loved the mod so much, so sad.

**Comment by devopsdinosaur** [comment]
Hello Veronica,

Thank you for the heads up.  I am working on my mods now to make sure they
will work with 0.8.  Craft from Storage is my first project, and I will try
to get it released today on nexusmods.

dd

**Comment by devopsdinosaur** [comment]
Seems to be working fine now with Sun Haven 1.0.

**Comment by ctrufan** [comment]
I just downloaded it with Sun Haven 1.0 and it doesn't seem to work - the "store all" button worked after a night's sleep from when I first installed the mod, but none of the crafting stations (Anvil, carpenter's station, etc) seem to be picking up on chests that are in my house.

**Comment by ctrufan** [comment]
Nevermind, my mistake! My "store all" button wasn't working again, so I tested a hunch and I realized that my house counts as a different 'zone' for the purposes of the mod, so it was user error!

May be worth adding a minor note to the disclaimer about zones that inside buildings count as different zones. Great mod!

**Comment by devopsdinosaur** [comment]
Hey Chris,

Yes, there is a note about that very fact on the nexus page for the mod.
It is really annoying the way the code handles storage and goes back to the
way Unity handles "scenes".  I'm planning to eventually add more
infrastructure code to the mod to rewrite the underlying storage system to
work around this fact and allow access to all storage from anywhere, but it
takes a bit more work, and I don't get paid for this =P

In the meantime I might try to add a label somewhere on the crafting
station that reiterates this limitation somehow.  Anyway, thanks for the
heads up.

dd
