### ISSUE TITLE
[time_management] Promenade skill from the Farming tree grants too much EXP

### ISSUE THREAD

**Issue by Lynvae** [devopsdinosaur/sunhaven-mods#28]
The Promenade skill from the farming tree (VII) is supposed to grant 2/4/6 exploration EXP per in-game hour, but with the Time Management mod this number is significantly higher (800-1300 EXP)

**Comment by devopsdinosaur** [comment]
Thanks for this info, Lynvae.  Should be resolved in v0.0.8 (just released on nexus).  Let me know and re-open this issue if not. -- dd
