### ISSUE TITLE
[no more watering] fertilizer not working

### ISSUE THREAD

**Issue by greycatsec** [devopsdinosaur/sunhaven-mods#32]
the particles don't show when Hide is set to false and the effects don't seem to take. I think the issue might be the name? They're called Earth2/Fire2  in the config, but the game calls them "Advanced Earth" "Advanced Fire". But fire/earth2 might be the underlying code that idk. please and thank you for looking into this <3

**Comment by greycatsec** [comment]
Ah. It works when you have the watering enabled. I just wanted the fertilizer functionality but after looking at the code, I've confirmed it's only when the watering is on. 

Is it possible to make them separate?

**Comment by devopsdinosaur** [comment]
You were absolutely correct.  Nice catch.

I just uploaded a new version (0.0.7) that seems to work to fertilize with the watering options disabled.  Let me know if it doesn't work for you (you can just re-open this ticket).

dd
