### ISSUE TITLE
[stack_size] Refuses to load in 1.3

### ISSUE THREAD

**Issue by savisitor15** [devopsdinosaur/sunhaven-mods#40]
It appears that update 1.3 has broken how item data is stored:

`[Info   :Stack Size] devopsdinosaur.sunhaven.stack_size v0.0.1 loaded.
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Wish.ItemDatabase and name ConstructDatabase and parameters (System.Collections.Generic.IList<Wish.ItemData>)`

**Comment by devopsdinosaur** [comment]
Thanks for the heads up.  Just uploaded a new version to nexus that seems
to work with v1.3.  Let me know if not. -- dd
