### ISSUE TITLE
[stack_size, bug] Multiple of the same animal not generating new items

### ISSUE THREAD

**Issue by ikamuzu** [devopsdinosaur/sunhaven-mods#52]
Hello! I'm running into a bug with the Sun Haven Stack Size Mod

Currently it seems like the mod messed with barn/coop animals, resulting in two issues:

1) If you have multiple e.g. chickens you can place them, collect their products and pick them up again. When you then place them again, all but the first animal will again offer their products, which can be repeated as often as you like. 

2) The mod makes it so that all but one of the animals of a given type will generate their item at the start of each day.

Obviously the first issue is minor - happy to just not do it - but the second makes it so that having more than one of any kind of animal is useless as long as the mod is on. This is easily one of the best QoL mods out there and I'd really hate to have to stop using it so that animals work correct. Is there a way to make it so that items that don't normally stack still don't stack with this mod? That might be what's causing the issue.

Thanks for all of your awesome work!

**Comment by devopsdinosaur** [comment]
Sorry for the delay on this @ikamuzu.  Checking it out now.  Shouldn't be a hard fix.

**Comment by ikamuzu** [comment]
No worries at all, thanks so much!!
